import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Form from '@/components/Form';
import { DishesData } from '@/types';
import useForm from '@/hooks/useForm';

export default function Home() {
  const { sendDishes } = useForm();

  const handleSubmit = async (values: DishesData) => {
    const response = await sendDishes(values);

    console.log(response);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Form onSubmit={handleSubmit} />
      </main>
    </>
  );
}
