import Head from 'next/head';
import Form from '@/components/Form/Form';
import { DishesData } from '@/types';
import useForm from '@/hooks/useForm';
import { useState } from 'react';
import Dishes from '@/components/Dishes/Dishes';
import { Box } from '@mui/material';
import AppBar from '@/components/AppBar';
import FormContainer from '@/components/Form/FormContainer';
import DishesContainer from '@/components/Dishes/DishesContainer';

export default function Home() {
  const [dishes, setDishes] = useState<DishesData[]>([]);

  const { sendDishes } = useForm();

  const handleSubmit = async (values: DishesData) => {
    const response = await sendDishes(values);

    setDishes((prev) => [...prev, response]);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}
      >
        <AppBar />
        <Box
          sx={{
            display: 'flex',
            flexDirection: { xs: 'column', md: 'row' },
            flex: 1,
          }}
        >
          <FormContainer>
            <Form onSubmit={handleSubmit} />
          </FormContainer>
          <DishesContainer>
            <Dishes dishes={dishes} />
          </DishesContainer>
        </Box>
      </Box>
    </>
  );
}
